// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace FunctionalTests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Test to see if we can login correctly as we start up the application
        /// </summary>
        public void LoginUITest()
        {
            #region Variable Declarations
            WinEdit uIAdresenzoekbalkEdit = this.UINieuwtabbladGoogleChWindow.UIItemGroup.UIAdresenzoekbalkEdit;
            WinWindow uIHomePageGoogleChromeWindow = this.UINieuwtabbladGoogleChWindow.UIHomePageGoogleChromeWindow;
            #endregion

            // Launch '%ProgramFiles(x86)%\Google\Chrome\Application\chrome.exe'
            ApplicationUnderTest uINieuwtabbladGoogleChWindow = ApplicationUnderTest.Launch(this.LoginUITestParams.UINieuwtabbladGoogleChWindowExePath, this.LoginUITestParams.UINieuwtabbladGoogleChWindowAlternateExePath);

            // Click 'Adres- en zoekbalk' text box
            Mouse.Click(uIAdresenzoekbalkEdit, new Point(63, 11));

            // Type 'localhost:{LShiftKey}49942{Enter}' in 'Adres- en zoekbalk' text box
            Keyboard.SendKeys(uIAdresenzoekbalkEdit, this.LoginUITestParams.UIAdresenzoekbalkEditSendKeys, ModifierKeys.None);

            // Click 'Home Page - Google Chrome' window
            Mouse.Click(uIHomePageGoogleChromeWindow, new Point(764, 127));

            // Click 'Home Page - Google Chrome' window
            Mouse.Click(uIHomePageGoogleChromeWindow, new Point(210, 272));

            // Type 'jan{LControlKey}' in 'Adres- en zoekbalk' text box
            Keyboard.SendKeys(uIAdresenzoekbalkEdit, this.LoginUITestParams.UIAdresenzoekbalkEditSendKeys1, ModifierKeys.None);

            // Type 'Alt, Control + 2' in 'Adres- en zoekbalk' text box
            Keyboard.SendKeys(uIAdresenzoekbalkEdit, this.LoginUITestParams.UIAdresenzoekbalkEditSendKeys2, (ModifierKeys.Alt | ModifierKeys.Control));

            // Type 'test{LShiftKey}.be' in 'Adres- en zoekbalk' text box
            Keyboard.SendKeys(uIAdresenzoekbalkEdit, this.LoginUITestParams.UIAdresenzoekbalkEditSendKeys3, ModifierKeys.None);

            // Click 'Home Page - Google Chrome' window
            Mouse.Click(uIHomePageGoogleChromeWindow, new Point(133, 342));

            // Type 'Control + a' in 'Adres- en zoekbalk' text box
            Keyboard.SendKeys(uIAdresenzoekbalkEdit, this.LoginUITestParams.UIAdresenzoekbalkEditSendKeys4, ModifierKeys.Control);

            // Type '{Back}{LShiftKey}Test{LControlKey}' in 'Adres- en zoekbalk' text box
            Keyboard.SendKeys(uIAdresenzoekbalkEdit, this.LoginUITestParams.UIAdresenzoekbalkEditSendKeys5, ModifierKeys.None);

            // Type 'Alt, Control + 2' in 'Adres- en zoekbalk' text box
            Keyboard.SendKeys(uIAdresenzoekbalkEdit, this.LoginUITestParams.UIAdresenzoekbalkEditSendKeys6, (ModifierKeys.Alt | ModifierKeys.Control));

            // Type 'Jan{LShiftKey}123' in 'Adres- en zoekbalk' text box
            Keyboard.SendKeys(uIAdresenzoekbalkEdit, this.LoginUITestParams.UIAdresenzoekbalkEditSendKeys7, ModifierKeys.None);

            // Click 'Home Page - Google Chrome' window
            Mouse.Click(uIHomePageGoogleChromeWindow, new Point(671, 383));
        }
        
        /// <summary>
        /// Testing Login Feature
        /// </summary>
        public void LoginTestUi()
        {
            #region Variable Declarations
            WinEdit uIAdresenzoekbalkEdit = this.UINieuwtabbladGoogleChWindow.UIItemGroup.UIAdresenzoekbalkEdit;
            WinWindow uIHomePageGoogleChromeWindow = this.UINieuwtabbladGoogleChWindow.UIHomePageGoogleChromeWindow;
            #endregion

            // Launch '%ProgramFiles(x86)%\Google\Chrome\Application\chrome.exe'
            ApplicationUnderTest uINieuwtabbladGoogleChWindow = ApplicationUnderTest.Launch(this.LoginTestUiParams.UINieuwtabbladGoogleChWindowExePath, this.LoginTestUiParams.UINieuwtabbladGoogleChWindowAlternateExePath);

            // Click 'Adres- en zoekbalk' text box
            Mouse.Click(uIAdresenzoekbalkEdit, new Point(35, 8));

            // Type 'local{Enter}' in 'Adres- en zoekbalk' text box
            Keyboard.SendKeys(uIAdresenzoekbalkEdit, this.LoginTestUiParams.UIAdresenzoekbalkEditSendKeys, ModifierKeys.None);

            // Click 'Home Page - Google Chrome' window
            Mouse.Click(uIHomePageGoogleChromeWindow, new Point(1489, 116));

            // Click 'Home Page - Google Chrome' window
            Mouse.Click(uIHomePageGoogleChromeWindow, new Point(507, 260));

            // Type 'sam{LControlKey}' in 'Adres- en zoekbalk' text box
            Keyboard.SendKeys(uIAdresenzoekbalkEdit, this.LoginTestUiParams.UIAdresenzoekbalkEditSendKeys1, ModifierKeys.None);

            // Type 'Alt, Control + 2' in 'Adres- en zoekbalk' text box
            Keyboard.SendKeys(uIAdresenzoekbalkEdit, this.LoginTestUiParams.UIAdresenzoekbalkEditSendKeys2, (ModifierKeys.Alt | ModifierKeys.Control));

            // Type 'test{LShiftKey}.be{Tab}{LShiftKey}Test{LControlKey}' in 'Adres- en zoekbalk' text box
            Keyboard.SendKeys(uIAdresenzoekbalkEdit, this.LoginTestUiParams.UIAdresenzoekbalkEditSendKeys3, ModifierKeys.None);

            // Type 'Alt, Control + 2' in 'Adres- en zoekbalk' text box
            Keyboard.SendKeys(uIAdresenzoekbalkEdit, this.LoginTestUiParams.UIAdresenzoekbalkEditSendKeys4, (ModifierKeys.Alt | ModifierKeys.Control));

            // Type 'Sam{LShiftKey}123' in 'Adres- en zoekbalk' text box
            Keyboard.SendKeys(uIAdresenzoekbalkEdit, this.LoginTestUiParams.UIAdresenzoekbalkEditSendKeys5, ModifierKeys.None);

            // Click 'Home Page - Google Chrome' window
            Mouse.Click(uIHomePageGoogleChromeWindow, new Point(1400, 372));
        }
        
        /// <summary>
        /// Test login feature
        /// </summary>
        public void TestLogin()
        {
            #region Variable Declarations
            WinEdit uIAdresenzoekbalkEdit = this.UINieuwtabbladGoogleChWindow.UIItemGroup.UIAdresenzoekbalkEdit;
            WinWindow uIHomePageGoogleChromeWindow = this.UINieuwtabbladGoogleChWindow.UIHomePageGoogleChromeWindow;
            WinControl uIChromeLegacyWindowDocument = this.UINieuwtabbladGoogleChWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Launch '%ProgramFiles(x86)%\Google\Chrome\Application\chrome.exe'
            ApplicationUnderTest uINieuwtabbladGoogleChWindow = ApplicationUnderTest.Launch(this.TestLoginParams.UINieuwtabbladGoogleChWindowExePath, this.TestLoginParams.UINieuwtabbladGoogleChWindowAlternateExePath);

            // Click 'Adres- en zoekbalk' text box
            Mouse.Click(uIAdresenzoekbalkEdit, new Point(36, 3));

            // Type 'localhost:{LShiftKey}49942{Enter}' in 'Adres- en zoekbalk' text box
            Keyboard.SendKeys(uIAdresenzoekbalkEdit, this.TestLoginParams.UIAdresenzoekbalkEditSendKeys, ModifierKeys.None);

            // Click 'Home Page - Google Chrome' window
            Mouse.Click(uIHomePageGoogleChromeWindow, new Point(1484, 117));

            // Click 'Home Page - Google Chrome' window
            Mouse.Click(uIHomePageGoogleChromeWindow, new Point(943, 221));

            // Type 'sam{LControlKey}' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.TestLoginParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Type 'Alt, Control + 2' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.TestLoginParams.UIChromeLegacyWindowDocumentSendKeys1, (ModifierKeys.Alt | ModifierKeys.Control));

            // Type 'test{LShiftKey}.be{Tab}{LShiftKey}Test{LControlKey}' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.TestLoginParams.UIChromeLegacyWindowDocumentSendKeys2, ModifierKeys.None);

            // Type 'Alt, Control + 2' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.TestLoginParams.UIChromeLegacyWindowDocumentSendKeys3, (ModifierKeys.Alt | ModifierKeys.Control));

            // Type 'Sam{LShiftKey}123' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.TestLoginParams.UIChromeLegacyWindowDocumentSendKeys4, ModifierKeys.None);

            // Click 'Home Page - Google Chrome' window
            Mouse.Click(uIHomePageGoogleChromeWindow, new Point(1024, 309));
        }
        
        /// <summary>
        /// Test Login Feature on Mozilla
        /// </summary>
        public void TestLoginFireFox()
        {
            #region Variable Declarations
            WinComboBox uIItemComboBox = this.UIMozillaFirefoxstartpWindow.UINavigatiewerkbalkToolBar.UIItemComboBox;
            WinEdit uIVoerzoektermofadresiEdit = this.UIMozillaFirefoxstartpWindow.UIItemComboBox.UIVoerzoektermofadresiEdit;
            WinEdit uILoginEdit = this.UIMozillaFirefoxstartpWindow.UILoginHyperlink.UILoginEdit;
            WinEdit uIEmailEdit = this.UIMozillaFirefoxstartpWindow.UIHomePageDocument.UIEmailEdit;
            WinEdit uIPasswordEdit = this.UIMozillaFirefoxstartpWindow.UIHomePageDocument.UIPasswordEdit;
            WinButton uILoginButton = this.UIMozillaFirefoxstartpWindow.UIHomePageDocument.UILoginButton;
            #endregion

            // Launch '%ProgramFiles(x86)%\Mozilla Firefox\firefox.exe'
            ApplicationUnderTest firefoxApplication = ApplicationUnderTest.Launch(this.TestLoginFireFoxParams.ExePath, this.TestLoginFireFoxParams.AlternateExePath);

            // Select 'localhost:49942' in combo box
            uIItemComboBox.EditableItem = this.TestLoginFireFoxParams.UIItemComboBoxEditableItem;

            // Type '{Enter}' in 'Voer zoekterm of adres in' text box
            Keyboard.SendKeys(uIVoerzoektermofadresiEdit, this.TestLoginFireFoxParams.UIVoerzoektermofadresiEditSendKeys, ModifierKeys.None);

            // Click 'Login' text box
            Mouse.Click(uILoginEdit, new Point(18, 10));

            // Type 'sam' in 'Email' text box
            uIEmailEdit.Text = this.TestLoginFireFoxParams.UIEmailEditText;

            // Type 'Alt, Control + 2' in 'Email' text box
            Keyboard.SendKeys(uIEmailEdit, this.TestLoginFireFoxParams.UIEmailEditSendKeys, (ModifierKeys.Alt | ModifierKeys.Control));

            // Type 'sam@test.be' in 'Email' text box
            uIEmailEdit.Text = this.TestLoginFireFoxParams.UIEmailEditText1;

            // Type '{Tab}' in 'Email' text box
            Keyboard.SendKeys(uIEmailEdit, this.TestLoginFireFoxParams.UIEmailEditSendKeys1, ModifierKeys.None);

            // Type '********' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.TestLoginFireFoxParams.UIPasswordEditSendKeys, true);

            // Type '********' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.TestLoginFireFoxParams.UIPasswordEditSendKeys1, (ModifierKeys.Alt | ModifierKeys.Control), true);

            // Type '********' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.TestLoginFireFoxParams.UIPasswordEditSendKeys2, true);

            // Click 'Login' button
            Mouse.Click(uILoginButton, new Point(42, 11));
        }
        
        /// <summary>
        /// Testing login functionality in firefox. Did not work in chrome
        /// </summary>
        public void LoginTestFireFox()
        {
            #region Variable Declarations
            WinComboBox uIItemComboBox = this.UIMozillaFirefoxstartpWindow.UINavigatiewerkbalkToolBar.UIItemComboBox;
            WinEdit uIVoerzoektermofadresiEdit = this.UIMozillaFirefoxstartpWindow.UIItemComboBox.UIVoerzoektermofadresiEdit;
            WinEdit uILoginEdit = this.UIMozillaFirefoxstartpWindow.UILoginHyperlink.UILoginEdit;
            WinEdit uIEmailEdit = this.UIMozillaFirefoxstartpWindow.UIHomePageDocument.UIEmailEdit;
            WinEdit uIPasswordEdit = this.UIMozillaFirefoxstartpWindow.UIHomePageDocument.UIPasswordEdit;
            WinButton uILoginButton = this.UIMozillaFirefoxstartpWindow.UIHomePageDocument.UILoginButton;
            WinEdit uIHeadquartersEdit = this.UIMozillaFirefoxstartpWindow.UIHeadquartersHyperlink.UIHeadquartersEdit;
            #endregion

            // Launch '%ProgramFiles(x86)%\Mozilla Firefox\firefox.exe'
            ApplicationUnderTest firefoxApplication = ApplicationUnderTest.Launch(this.LoginTestFireFoxParams.ExePath, this.LoginTestFireFoxParams.AlternateExePath);

            // Select 'localhost:49942' in combo box
            uIItemComboBox.EditableItem = this.LoginTestFireFoxParams.UIItemComboBoxEditableItem;

            // Type '{Enter}' in 'Voer zoekterm of adres in' text box
            Keyboard.SendKeys(uIVoerzoektermofadresiEdit, this.LoginTestFireFoxParams.UIVoerzoektermofadresiEditSendKeys, ModifierKeys.None);

            // Click 'Login' text box
            Mouse.Click(uILoginEdit, new Point(17, 8));

            // Type 'jan' in 'Email' text box
            uIEmailEdit.Text = this.LoginTestFireFoxParams.UIEmailEditText;

            // Type 'Alt, Control + 2' in 'Email' text box
            Keyboard.SendKeys(uIEmailEdit, this.LoginTestFireFoxParams.UIEmailEditSendKeys, (ModifierKeys.Alt | ModifierKeys.Control));

            // Type 'jan@test.be' in 'Email' text box
            uIEmailEdit.Text = this.LoginTestFireFoxParams.UIEmailEditText1;

            // Type '{Tab}' in 'Email' text box
            Keyboard.SendKeys(uIEmailEdit, this.LoginTestFireFoxParams.UIEmailEditSendKeys1, ModifierKeys.None);

            // Type '********' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.LoginTestFireFoxParams.UIPasswordEditSendKeys, true);

            // Type '********' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.LoginTestFireFoxParams.UIPasswordEditSendKeys1, (ModifierKeys.Alt | ModifierKeys.Control), true);

            // Type '********' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.LoginTestFireFoxParams.UIPasswordEditSendKeys2, true);

            // Click 'Login' button
            Mouse.Click(uILoginButton, new Point(39, 20));

            // Click 'Headquarters' text box
            Mouse.Click(uIHeadquartersEdit, new Point(59, 10));
        }
        
        /// <summary>
        /// This test should try to login using a wrong password
        /// </summary>
        public void LoginFailTestFireFox()
        {
            #region Variable Declarations
            WinComboBox uIItemComboBox = this.UIMozillaFirefoxstartpWindow.UINavigatiewerkbalkToolBar.UIItemComboBox;
            WinEdit uIVoerzoektermofadresiEdit = this.UIMozillaFirefoxstartpWindow.UIItemComboBox.UIVoerzoektermofadresiEdit;
            WinEdit uILoginEdit = this.UIMozillaFirefoxstartpWindow.UILoginHyperlink.UILoginEdit;
            WinEdit uIEmailEdit = this.UIMozillaFirefoxstartpWindow.UIHomePageDocument.UIEmailEdit;
            WinEdit uIPasswordEdit = this.UIMozillaFirefoxstartpWindow.UIHomePageDocument.UIPasswordEdit;
            WinButton uILoginButton = this.UIMozillaFirefoxstartpWindow.UIHomePageDocument.UILoginButton;
            WinButton uIOKButton = this.UIMozillaFirefoxstartpWindow.UIItemDialog.UIOKButton;
            #endregion

            // Launch '%ProgramFiles(x86)%\Mozilla Firefox\firefox.exe'
            ApplicationUnderTest firefoxApplication = ApplicationUnderTest.Launch(this.LoginFailTestFireFoxParams.ExePath, this.LoginFailTestFireFoxParams.AlternateExePath);

            // Select 'localhost:49942' in combo box
            uIItemComboBox.EditableItem = this.LoginFailTestFireFoxParams.UIItemComboBoxEditableItem;

            // Type '{Enter}' in 'Voer zoekterm of adres in' text box
            Keyboard.SendKeys(uIVoerzoektermofadresiEdit, this.LoginFailTestFireFoxParams.UIVoerzoektermofadresiEditSendKeys, ModifierKeys.None);

            // Click 'Login' text box
            Mouse.Click(uILoginEdit, new Point(37, 17));

            // Type 'jan' in 'Email' text box
            uIEmailEdit.Text = this.LoginFailTestFireFoxParams.UIEmailEditText;

            // Type 'Alt, Control + 2' in 'Email' text box
            Keyboard.SendKeys(uIEmailEdit, this.LoginFailTestFireFoxParams.UIEmailEditSendKeys, (ModifierKeys.Alt | ModifierKeys.Control));

            // Type 'jan@test.be' in 'Email' text box
            uIEmailEdit.Text = this.LoginFailTestFireFoxParams.UIEmailEditText1;

            // Type '{Tab}' in 'Email' text box
            Keyboard.SendKeys(uIEmailEdit, this.LoginFailTestFireFoxParams.UIEmailEditSendKeys1, ModifierKeys.None);

            // Type '********' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.LoginFailTestFireFoxParams.UIPasswordEditSendKeys, true);

            // Click 'Login' button
            Mouse.Click(uILoginButton, new Point(41, 21));

            // Click 'OK' button
            Mouse.Click(uIOKButton, new Point(52, 15));
        }
        
        #region Properties
        public virtual LoginUITestParams LoginUITestParams
        {
            get
            {
                if ((this.mLoginUITestParams == null))
                {
                    this.mLoginUITestParams = new LoginUITestParams();
                }
                return this.mLoginUITestParams;
            }
        }
        
        public virtual LoginTestUiParams LoginTestUiParams
        {
            get
            {
                if ((this.mLoginTestUiParams == null))
                {
                    this.mLoginTestUiParams = new LoginTestUiParams();
                }
                return this.mLoginTestUiParams;
            }
        }
        
        public virtual TestLoginParams TestLoginParams
        {
            get
            {
                if ((this.mTestLoginParams == null))
                {
                    this.mTestLoginParams = new TestLoginParams();
                }
                return this.mTestLoginParams;
            }
        }
        
        public virtual TestLoginFireFoxParams TestLoginFireFoxParams
        {
            get
            {
                if ((this.mTestLoginFireFoxParams == null))
                {
                    this.mTestLoginFireFoxParams = new TestLoginFireFoxParams();
                }
                return this.mTestLoginFireFoxParams;
            }
        }
        
        public virtual LoginTestFireFoxParams LoginTestFireFoxParams
        {
            get
            {
                if ((this.mLoginTestFireFoxParams == null))
                {
                    this.mLoginTestFireFoxParams = new LoginTestFireFoxParams();
                }
                return this.mLoginTestFireFoxParams;
            }
        }
        
        public virtual LoginFailTestFireFoxParams LoginFailTestFireFoxParams
        {
            get
            {
                if ((this.mLoginFailTestFireFoxParams == null))
                {
                    this.mLoginFailTestFireFoxParams = new LoginFailTestFireFoxParams();
                }
                return this.mLoginFailTestFireFoxParams;
            }
        }
        
        public UINieuwtabbladGoogleChWindow UINieuwtabbladGoogleChWindow
        {
            get
            {
                if ((this.mUINieuwtabbladGoogleChWindow == null))
                {
                    this.mUINieuwtabbladGoogleChWindow = new UINieuwtabbladGoogleChWindow();
                }
                return this.mUINieuwtabbladGoogleChWindow;
            }
        }
        
        public UIMozillaFirefoxstartpWindow UIMozillaFirefoxstartpWindow
        {
            get
            {
                if ((this.mUIMozillaFirefoxstartpWindow == null))
                {
                    this.mUIMozillaFirefoxstartpWindow = new UIMozillaFirefoxstartpWindow();
                }
                return this.mUIMozillaFirefoxstartpWindow;
            }
        }
        #endregion
        
        #region Fields
        private LoginUITestParams mLoginUITestParams;
        
        private LoginTestUiParams mLoginTestUiParams;
        
        private TestLoginParams mTestLoginParams;
        
        private TestLoginFireFoxParams mTestLoginFireFoxParams;
        
        private LoginTestFireFoxParams mLoginTestFireFoxParams;
        
        private LoginFailTestFireFoxParams mLoginFailTestFireFoxParams;
        
        private UINieuwtabbladGoogleChWindow mUINieuwtabbladGoogleChWindow;
        
        private UIMozillaFirefoxstartpWindow mUIMozillaFirefoxstartpWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LoginUITest'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class LoginUITestParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%ProgramFiles(x86)%\Google\Chrome\Application\chrome.exe'
        /// </summary>
        public string UINieuwtabbladGoogleChWindowExePath = "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe";
        
        /// <summary>
        /// Launch '%ProgramFiles(x86)%\Google\Chrome\Application\chrome.exe'
        /// </summary>
        public string UINieuwtabbladGoogleChWindowAlternateExePath = "%ProgramFiles(x86)%\\Google\\Chrome\\Application\\chrome.exe";
        
        /// <summary>
        /// Type 'localhost:{LShiftKey}49942{Enter}' in 'Adres- en zoekbalk' text box
        /// </summary>
        public string UIAdresenzoekbalkEditSendKeys = "localhost:{LShiftKey}49942{Enter}";
        
        /// <summary>
        /// Type 'jan{LControlKey}' in 'Adres- en zoekbalk' text box
        /// </summary>
        public string UIAdresenzoekbalkEditSendKeys1 = "jan{LControlKey}";
        
        /// <summary>
        /// Type 'Alt, Control + 2' in 'Adres- en zoekbalk' text box
        /// </summary>
        public string UIAdresenzoekbalkEditSendKeys2 = "2";
        
        /// <summary>
        /// Type 'test{LShiftKey}.be' in 'Adres- en zoekbalk' text box
        /// </summary>
        public string UIAdresenzoekbalkEditSendKeys3 = "test{LShiftKey}.be";
        
        /// <summary>
        /// Type 'Control + a' in 'Adres- en zoekbalk' text box
        /// </summary>
        public string UIAdresenzoekbalkEditSendKeys4 = "a";
        
        /// <summary>
        /// Type '{Back}{LShiftKey}Test{LControlKey}' in 'Adres- en zoekbalk' text box
        /// </summary>
        public string UIAdresenzoekbalkEditSendKeys5 = "{Back}{LShiftKey}Test{LControlKey}";
        
        /// <summary>
        /// Type 'Alt, Control + 2' in 'Adres- en zoekbalk' text box
        /// </summary>
        public string UIAdresenzoekbalkEditSendKeys6 = "2";
        
        /// <summary>
        /// Type 'Jan{LShiftKey}123' in 'Adres- en zoekbalk' text box
        /// </summary>
        public string UIAdresenzoekbalkEditSendKeys7 = "Jan{LShiftKey}123";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LoginTestUi'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class LoginTestUiParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%ProgramFiles(x86)%\Google\Chrome\Application\chrome.exe'
        /// </summary>
        public string UINieuwtabbladGoogleChWindowExePath = "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe";
        
        /// <summary>
        /// Launch '%ProgramFiles(x86)%\Google\Chrome\Application\chrome.exe'
        /// </summary>
        public string UINieuwtabbladGoogleChWindowAlternateExePath = "%ProgramFiles(x86)%\\Google\\Chrome\\Application\\chrome.exe";
        
        /// <summary>
        /// Type 'local{Enter}' in 'Adres- en zoekbalk' text box
        /// </summary>
        public string UIAdresenzoekbalkEditSendKeys = "local{Enter}";
        
        /// <summary>
        /// Type 'sam{LControlKey}' in 'Adres- en zoekbalk' text box
        /// </summary>
        public string UIAdresenzoekbalkEditSendKeys1 = "sam{LControlKey}";
        
        /// <summary>
        /// Type 'Alt, Control + 2' in 'Adres- en zoekbalk' text box
        /// </summary>
        public string UIAdresenzoekbalkEditSendKeys2 = "2";
        
        /// <summary>
        /// Type 'test{LShiftKey}.be{Tab}{LShiftKey}Test{LControlKey}' in 'Adres- en zoekbalk' text box
        /// </summary>
        public string UIAdresenzoekbalkEditSendKeys3 = "test{LShiftKey}.be{Tab}{LShiftKey}Test{LControlKey}";
        
        /// <summary>
        /// Type 'Alt, Control + 2' in 'Adres- en zoekbalk' text box
        /// </summary>
        public string UIAdresenzoekbalkEditSendKeys4 = "2";
        
        /// <summary>
        /// Type 'Sam{LShiftKey}123' in 'Adres- en zoekbalk' text box
        /// </summary>
        public string UIAdresenzoekbalkEditSendKeys5 = "Sam{LShiftKey}123";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestLogin'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class TestLoginParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%ProgramFiles(x86)%\Google\Chrome\Application\chrome.exe'
        /// </summary>
        public string UINieuwtabbladGoogleChWindowExePath = "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe";
        
        /// <summary>
        /// Launch '%ProgramFiles(x86)%\Google\Chrome\Application\chrome.exe'
        /// </summary>
        public string UINieuwtabbladGoogleChWindowAlternateExePath = "%ProgramFiles(x86)%\\Google\\Chrome\\Application\\chrome.exe";
        
        /// <summary>
        /// Type 'localhost:{LShiftKey}49942{Enter}' in 'Adres- en zoekbalk' text box
        /// </summary>
        public string UIAdresenzoekbalkEditSendKeys = "localhost:{LShiftKey}49942{Enter}";
        
        /// <summary>
        /// Type 'sam{LControlKey}' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "sam{LControlKey}";
        
        /// <summary>
        /// Type 'Alt, Control + 2' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "2";
        
        /// <summary>
        /// Type 'test{LShiftKey}.be{Tab}{LShiftKey}Test{LControlKey}' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys2 = "test{LShiftKey}.be{Tab}{LShiftKey}Test{LControlKey}";
        
        /// <summary>
        /// Type 'Alt, Control + 2' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys3 = "2";
        
        /// <summary>
        /// Type 'Sam{LShiftKey}123' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys4 = "Sam{LShiftKey}123";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestLoginFireFox'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class TestLoginFireFoxParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%ProgramFiles(x86)%\Mozilla Firefox\firefox.exe'
        /// </summary>
        public string ExePath = "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe";
        
        /// <summary>
        /// Launch '%ProgramFiles(x86)%\Mozilla Firefox\firefox.exe'
        /// </summary>
        public string AlternateExePath = "%ProgramFiles(x86)%\\Mozilla Firefox\\firefox.exe";
        
        /// <summary>
        /// Select 'localhost:49942' in combo box
        /// </summary>
        public string UIItemComboBoxEditableItem = "localhost:49942";
        
        /// <summary>
        /// Type '{Enter}' in 'Voer zoekterm of adres in' text box
        /// </summary>
        public string UIVoerzoektermofadresiEditSendKeys = "{Enter}";
        
        /// <summary>
        /// Type 'sam' in 'Email' text box
        /// </summary>
        public string UIEmailEditText = "sam";
        
        /// <summary>
        /// Type 'Alt, Control + 2' in 'Email' text box
        /// </summary>
        public string UIEmailEditSendKeys = "2";
        
        /// <summary>
        /// Type 'sam@test.be' in 'Email' text box
        /// </summary>
        public string UIEmailEditText1 = "sam@test.be";
        
        /// <summary>
        /// Type '{Tab}' in 'Email' text box
        /// </summary>
        public string UIEmailEditSendKeys1 = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "ZvWPcERypgfVi9dmQDpp3IHjRe7N10Rah84UY6UfiT8=";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys1 = "nlpHdv/bx30HDttDrfmCSw==";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys2 = "tbhlw262cr5b7notXNtBgGysJASiu8MZt9G2DpJHqLw=";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LoginTestFireFox'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class LoginTestFireFoxParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%ProgramFiles(x86)%\Mozilla Firefox\firefox.exe'
        /// </summary>
        public string ExePath = "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe";
        
        /// <summary>
        /// Launch '%ProgramFiles(x86)%\Mozilla Firefox\firefox.exe'
        /// </summary>
        public string AlternateExePath = "%ProgramFiles(x86)%\\Mozilla Firefox\\firefox.exe";
        
        /// <summary>
        /// Select 'localhost:49942' in combo box
        /// </summary>
        public string UIItemComboBoxEditableItem = "localhost:49942";
        
        /// <summary>
        /// Type '{Enter}' in 'Voer zoekterm of adres in' text box
        /// </summary>
        public string UIVoerzoektermofadresiEditSendKeys = "{Enter}";
        
        /// <summary>
        /// Type 'jan' in 'Email' text box
        /// </summary>
        public string UIEmailEditText = "jan";
        
        /// <summary>
        /// Type 'Alt, Control + 2' in 'Email' text box
        /// </summary>
        public string UIEmailEditSendKeys = "2";
        
        /// <summary>
        /// Type 'jan@test.be' in 'Email' text box
        /// </summary>
        public string UIEmailEditText1 = "jan@test.be";
        
        /// <summary>
        /// Type '{Tab}' in 'Email' text box
        /// </summary>
        public string UIEmailEditSendKeys1 = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "ZvWPcERypgfVi9dmQDpp3IHjRe7N10Rah84UY6UfiT8=";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys1 = "nlpHdv/bx30HDttDrfmCSw==";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys2 = "w8tnspdlP7KACgB7rzZUgkChwQnhrzowGuw7MfX3rS4=";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LoginFailTestFireFox'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class LoginFailTestFireFoxParams
    {
        
        #region Fields
        /// <summary>
        /// Launch '%ProgramFiles(x86)%\Mozilla Firefox\firefox.exe'
        /// </summary>
        public string ExePath = "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe";
        
        /// <summary>
        /// Launch '%ProgramFiles(x86)%\Mozilla Firefox\firefox.exe'
        /// </summary>
        public string AlternateExePath = "%ProgramFiles(x86)%\\Mozilla Firefox\\firefox.exe";
        
        /// <summary>
        /// Select 'localhost:49942' in combo box
        /// </summary>
        public string UIItemComboBoxEditableItem = "localhost:49942";
        
        /// <summary>
        /// Type '{Enter}' in 'Voer zoekterm of adres in' text box
        /// </summary>
        public string UIVoerzoektermofadresiEditSendKeys = "{Enter}";
        
        /// <summary>
        /// Type 'jan' in 'Email' text box
        /// </summary>
        public string UIEmailEditText = "jan";
        
        /// <summary>
        /// Type 'Alt, Control + 2' in 'Email' text box
        /// </summary>
        public string UIEmailEditSendKeys = "2";
        
        /// <summary>
        /// Type 'jan@test.be' in 'Email' text box
        /// </summary>
        public string UIEmailEditText1 = "jan@test.be";
        
        /// <summary>
        /// Type '{Tab}' in 'Email' text box
        /// </summary>
        public string UIEmailEditSendKeys1 = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "lDf6jAWgCgAlxzmYEbvjCaK9LImmNxDC";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UINieuwtabbladGoogleChWindow : WinWindow
    {
        
        public UINieuwtabbladGoogleChWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Nieuw tabblad - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Nieuw tabblad - Google Chrome");
            this.WindowTitles.Add("Home Page - Google Chrome");
            #endregion
        }
        
        #region Properties
        public UIItemGroup UIItemGroup
        {
            get
            {
                if ((this.mUIItemGroup == null))
                {
                    this.mUIItemGroup = new UIItemGroup(this);
                }
                return this.mUIItemGroup;
            }
        }
        
        public WinWindow UIHomePageGoogleChromeWindow
        {
            get
            {
                if ((this.mUIHomePageGoogleChromeWindow == null))
                {
                    this.mUIHomePageGoogleChromeWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIHomePageGoogleChromeWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Home Page - Google Chrome";
                    this.mUIHomePageGoogleChromeWindow.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    this.mUIHomePageGoogleChromeWindow.WindowTitles.Add("Home Page - Google Chrome");
                    #endregion
                }
                return this.mUIHomePageGoogleChromeWindow;
            }
        }
        
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemGroup mUIItemGroup;
        
        private WinWindow mUIHomePageGoogleChromeWindow;
        
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemGroup : WinGroup
    {
        
        public UIItemGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Nieuw tabblad - Google Chrome");
            this.WindowTitles.Add("Home Page - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAdresenzoekbalkEdit
        {
            get
            {
                if ((this.mUIAdresenzoekbalkEdit == null))
                {
                    this.mUIAdresenzoekbalkEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAdresenzoekbalkEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Adres- en zoekbalk";
                    this.mUIAdresenzoekbalkEdit.WindowTitles.Add("Nieuw tabblad - Google Chrome");
                    this.mUIAdresenzoekbalkEdit.WindowTitles.Add("Home Page - Google Chrome");
                    #endregion
                }
                return this.mUIAdresenzoekbalkEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAdresenzoekbalkEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "240983648";
            this.WindowTitles.Add("Home Page - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Home Page - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMozillaFirefoxstartpWindow : WinWindow
    {
        
        public UIMozillaFirefoxstartpWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Mozilla Firefox-startpagina - Mozilla Firefox";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MozillaWindowClass";
            this.WindowTitles.Add("Mozilla Firefox-startpagina - Mozilla Firefox");
            this.WindowTitles.Add("Home Page - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public UINavigatiewerkbalkToolBar UINavigatiewerkbalkToolBar
        {
            get
            {
                if ((this.mUINavigatiewerkbalkToolBar == null))
                {
                    this.mUINavigatiewerkbalkToolBar = new UINavigatiewerkbalkToolBar(this);
                }
                return this.mUINavigatiewerkbalkToolBar;
            }
        }
        
        public UIItemComboBox UIItemComboBox
        {
            get
            {
                if ((this.mUIItemComboBox == null))
                {
                    this.mUIItemComboBox = new UIItemComboBox(this);
                }
                return this.mUIItemComboBox;
            }
        }
        
        public UILoginHyperlink UILoginHyperlink
        {
            get
            {
                if ((this.mUILoginHyperlink == null))
                {
                    this.mUILoginHyperlink = new UILoginHyperlink(this);
                }
                return this.mUILoginHyperlink;
            }
        }
        
        public UIHomePageDocument UIHomePageDocument
        {
            get
            {
                if ((this.mUIHomePageDocument == null))
                {
                    this.mUIHomePageDocument = new UIHomePageDocument(this);
                }
                return this.mUIHomePageDocument;
            }
        }
        
        public UIHeadquartersHyperlink UIHeadquartersHyperlink
        {
            get
            {
                if ((this.mUIHeadquartersHyperlink == null))
                {
                    this.mUIHeadquartersHyperlink = new UIHeadquartersHyperlink(this);
                }
                return this.mUIHeadquartersHyperlink;
            }
        }
        
        public UIItemDialog UIItemDialog
        {
            get
            {
                if ((this.mUIItemDialog == null))
                {
                    this.mUIItemDialog = new UIItemDialog(this);
                }
                return this.mUIItemDialog;
            }
        }
        #endregion
        
        #region Fields
        private UINavigatiewerkbalkToolBar mUINavigatiewerkbalkToolBar;
        
        private UIItemComboBox mUIItemComboBox;
        
        private UILoginHyperlink mUILoginHyperlink;
        
        private UIHomePageDocument mUIHomePageDocument;
        
        private UIHeadquartersHyperlink mUIHeadquartersHyperlink;
        
        private UIItemDialog mUIItemDialog;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UINavigatiewerkbalkToolBar : WinToolBar
    {
        
        public UINavigatiewerkbalkToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Navigatiewerkbalk";
            this.WindowTitles.Add("Mozilla Firefox-startpagina - Mozilla Firefox");
            this.WindowTitles.Add("Home Page - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIItemComboBox
        {
            get
            {
                if ((this.mUIItemComboBox == null))
                {
                    this.mUIItemComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIItemComboBox.WindowTitles.Add("Mozilla Firefox-startpagina - Mozilla Firefox");
                    this.mUIItemComboBox.WindowTitles.Add("Home Page - Mozilla Firefox");
                    #endregion
                }
                return this.mUIItemComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIItemComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemComboBox : WinComboBox
    {
        
        public UIItemComboBox(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Mozilla Firefox-startpagina - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIVoerzoektermofadresiEdit
        {
            get
            {
                if ((this.mUIVoerzoektermofadresiEdit == null))
                {
                    this.mUIVoerzoektermofadresiEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIVoerzoektermofadresiEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Voer zoekterm of adres in";
                    this.mUIVoerzoektermofadresiEdit.WindowTitles.Add("Mozilla Firefox-startpagina - Mozilla Firefox");
                    #endregion
                }
                return this.mUIVoerzoektermofadresiEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIVoerzoektermofadresiEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILoginHyperlink : WinHyperlink
    {
        
        public UILoginHyperlink(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = "Login";
            this.WindowTitles.Add("Home Page - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UILoginEdit
        {
            get
            {
                if ((this.mUILoginEdit == null))
                {
                    this.mUILoginEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUILoginEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Login";
                    this.mUILoginEdit.WindowTitles.Add("Home Page - Mozilla Firefox");
                    #endregion
                }
                return this.mUILoginEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUILoginEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHomePageDocument : WinControl
    {
        
        public UIHomePageDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Home Page";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
            this.WindowTitles.Add("Home Page - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEmailEdit
        {
            get
            {
                if ((this.mUIEmailEdit == null))
                {
                    this.mUIEmailEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIEmailEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Email";
                    this.mUIEmailEdit.WindowTitles.Add("Home Page - Mozilla Firefox");
                    #endregion
                }
                return this.mUIEmailEdit;
            }
        }
        
        public WinEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Password";
                    this.mUIPasswordEdit.WindowTitles.Add("Home Page - Mozilla Firefox");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public WinButton UILoginButton
        {
            get
            {
                if ((this.mUILoginButton == null))
                {
                    this.mUILoginButton = new WinButton(this);
                    #region Search Criteria
                    this.mUILoginButton.SearchProperties[WinButton.PropertyNames.Name] = "Login";
                    this.mUILoginButton.WindowTitles.Add("Home Page - Mozilla Firefox");
                    #endregion
                }
                return this.mUILoginButton;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEmailEdit;
        
        private WinEdit mUIPasswordEdit;
        
        private WinButton mUILoginButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHeadquartersHyperlink : WinHyperlink
    {
        
        public UIHeadquartersHyperlink(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = "Headquarters";
            this.WindowTitles.Add("Home Page - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinEdit UIHeadquartersEdit
        {
            get
            {
                if ((this.mUIHeadquartersEdit == null))
                {
                    this.mUIHeadquartersEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIHeadquartersEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Headquarters";
                    this.mUIHeadquartersEdit.WindowTitles.Add("Home Page - Mozilla Firefox");
                    #endregion
                }
                return this.mUIHeadquartersEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIHeadquartersEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemDialog : WinControl
    {
        
        public UIItemDialog(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Dialog";
            this.WindowTitles.Add("Home Page - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Home Page - Mozilla Firefox");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
}
